### ISSUE TITLE
Option to filter auth requests by IP address

### ISSUE THREAD

**Issue by hughbris** [LincolnUniLTL/AlmEZ#2]
Potentially the script's (possibly) public URL could be used to script unlimited brute force login attempts. Restriction of requests by IP should prevent this.

Such filtering could also be implemented by an administrator at web server level. That could be used as interim workaround until this is implemented. Also, the script could be deployed on a different web server that is not publicly accessible. I think ultimately it's better to bundle this into the application though, for simplicity and traceability.

**Comment by LincolnUniLTL** [comment]
As of v.2.0 the script can now optionally verify the IP address of the caller.
