### ISSUE TITLE
Add option to put API key in HTTP header, not URL

### ISSUE THREAD

**Issue by hughbris** [LincolnUniLTL/AlmEZ#3]
[According to the Ex Libris Developer Network](https://developers.exlibrisgroup.com/alma/apis#calling), it's also possible to use the following header to authenticate RESTful web service calls:

    Authorization: apikey {APIKEY}

This is definitely preferable in an environment where the request URL (the way it is currently implemented) might be logged or insecurely transported.

**Comment by LincolnUniLTL** [comment]
As of v.2.0 the apikey defaults to being sent as a header (retaining the option to send it as a query string).
